server:
  port: 8004
websocket:
  port: 58041
  path: /ws
tcp:
  port: 58042
  enable: false
spring:
  profiles:
    active: dev
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      # 未定义的key不序列化(允许对象忽略json中不存在的属性)
      fail_on_unknown_properties: false
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
ipring:
  netty:
    server: 192.168.7.41:31265
  task-pool:
    core-size: 4
    max-size: 5
    keep-alive: 60
    queue-capacity: 200

zmq:
  subscribe-address:
    fb: tcp://quotespush.fastbull.com:5500
