server:
  port: 8100
spring:
  profiles:
    active: dev
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      # 未定义的key不序列化(允许对象忽略json中不存在的属性)
      fail_on_unknown_properties: false

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mapper
  mapper-locations:
    # *.xml的具体路径
    - classpath*:mapper/*.xml
