server:
  port: 8030
spring:
  profiles:
    active: dev
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      # 未定义的key不序列化(允许对象忽略json中不存在的属性)
      fail_on_unknown_properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.136.202:3306/activiti7?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: Root@123

ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0
