server:
  port: 8099
spring:
  jackson:
    deserialization:
      fail_on_unknown_properties: false # 未定义的key不序列化(允许对象忽略json中不存在的属性)
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.136.200:3306/bh_im?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#    username: root
#    password: Root@123
#    禁用redis
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  redis:
    # 地址
    host: 192.168.121.200
    # 端口，默认为6379
    port: 6379
    ssl: false
    # 密码
    password: admin
    # 连接超时时间
    timeout: 10000
    database: 0
    jedis:
      pool:
        max-active: 300
        max-idle: 100
        min-idle: 0
#        max-wait: 10000
ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0
  env:
    name: dev
