ipring:
  env:
    name: prod
  netty:
    server: 192.168.7.41:31265
  config:
    ct4-trader: https://ct-trader.toant.top
    ct4-account: https://ct-account.toant.top
zmq:
  subscribe-address:
    fb: tcp://quotespush.fastbull.com:5500
