server:
  port: 8011
spring:
  profiles:
    active: dev
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      fail_on_unknown_properties: false
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.136.200:3306/bh_im?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#    username: root
#    password: Root@123

#    禁用redis
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0
  env:
    name: dev
  netty:
    server: 192.168.7.41:31265
  config:
    svc:
      base: http://192.168.7.41:30400