server:
  port: 8001
spring:
  profiles:
    active: dev
  jackson:
    deserialization:
      fail_on_unknown_properties: false
ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0