server:
  port: 8003
spring:
  profiles:
    active: prod
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      fail_on_unknown_properties: false
ipring:
  task-pool:
    core-size: 20
    max-size: 20
    keep-alive: 60
    queue-capacity: 200
  swagger:
    enable: true
    name: "zmq"
    version: V1.0.0
  env:
    name: ${spring.profiles.active}
zmq:
  subscribe-address:
    local-one: tcp://localhost:58031
    local-two: tcp://localhost:58032
  publish-one: tcp://*:58031
  publish-two: tcp://*:58032

my:
  zmq:
    one: tcp://192.168.7.200:5600
    two: tcp://quotespush.fastbull.com:5500
