server:
  port: 8003
spring:
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      fail_on_unknown_properties: false
ipring:
  env:
    name: dev
zmq:
  subscribe-address:
    fb: tcp://192.168.7.41:31090
