server:
  port: 8003
spring:
  profiles:
    active: dev
ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0
  env:
    name: dev
  netty:
    server: 192.168.7.41:31265
  config:
    ct4: https://test-ct-trader.tostar.top
#      ct4: http://localhost:8083
  task-pool:
    core-size: 4
    max-size: 5
    keep-alive: 60
    queue-capacity: 200

zmq:
  subscribe-address:
    fb: tcp://quotespush.fastbull.com:5500
    local-one: tcp://localhost:58031
    local-two: tcp://localhost:58032
  publish-one: tcp://*:58031
  publish-two: tcp://*:58032

my:
  zmq:
    one: tcp://192.168.7.200:5600
    two: tcp://quotespush.fastbull.com:5500
