server:
  port: 8003
spring:
  profiles:
    active: dev


mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mapper
  mapper-locations:
    # *.xml的具体路径
    - classpath*:mapper/*.xml
ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0
  env:
    name: dev
  netty:
    server: 192.168.7.41:31265
  config:
    svc:
      base: http://192.168.7.41:30400
  task-pool:
    core-size: 4
    max-size: 5
    keep-alive: 60
    queue-capacity: 200

zmq:
  subscribe-address:
    fb: tcp://quotespush.fastbull.com:5500
    local-one: tcp://localhost:58031
    local-two: tcp://localhost:58032
  publish-one: tcp://*:58031
  publish-two: tcp://*:58032
