server:
  port: 8004
websocket:
  port: ${random.int[50000,59999]}
  heart-beat-gap: 10000 # 调长一点 省的本地测试的时候全是心跳
  heart-beat-check: 0 # 本地测试的客户端不需要检查
spring:
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      # 未定义的key不序列化(允许对象忽略json中不存在的属性)
      fail_on_unknown_properties: false
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.136.200:3306/bh_im?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#    username: root
#    password: Root@123

#    禁用redis
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
#      database:
#      host:
#      port:
#      password:
#      timeout:
#      lettuce:
#        pool:
#          enabled: true
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: 5000
#      address: redis://192.168.136.202:6379

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mapper
  mapper-locations:
    # *.xml的具体路径
    - classpath*:mapper/*.xml
ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0
  env:
    name: dev
  netty:
    server: 192.168.7.41:31265
  config:
    svc:
      base: http://192.168.7.41:30400


zmq:
  subscribe-address:
#    fb: tcp://192.168.7.41:31090
    fb: tcp://quotespush.fastbull.com:5500
