server:
  port: 8002
spring:
  profiles:
    active: dev
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      # 未定义的key不序列化(允许对象忽略json中不存在的属性)
      fail_on_unknown_properties: false
ipring:
  swagger:
    enable: true
    name: "校验服务"
    version: V1.0.0
