server:
  port: 8011
spring:
  profiles:
    active: dev
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      fail_on_unknown_properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.121.168:3306/customdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: Root@123


ipring:
  swagger:
    enable: true
    name: "框架相关"
    version: V1.0.0
  env:
    name: dev
  netty:
    server: 192.168.7.41:31265
  config:
    svc:
      base: http://192.168.7.41:30400
    ct4: http://192.168.1.80:8083