server:
  port: 8004
websocket:
  #  port: ${random.int[50000,59999]}
  port: 58041
  heart-beat-gap: 10000 # 调长一点 省的本地测试的时候全是心跳
  heart-beat-check: 0 # 本地测试的客户端不需要检查
tcp:
  port: 58042
spring:
  messages:
    basename: messages/messages
  jackson:
    deserialization:
      # 未定义的key不序列化(允许对象忽略json中不存在的属性)
      fail_on_unknown_properties: false
  #    禁用redis
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

ipring:
  netty:
    server: localhost:50042
  config:
    svc:
      base: http://192.168.7.41:30400


zmq:
  subscribe-address:
    #    fb: tcp://192.168.7.41:31090
    fb: tcp://quotespush.fastbull.com:5500
